language: node_js

node_js:
  - stable
branches:
  only:
    - master
 
script:
 - npm install -g firebase-tools  
 script: 
  - npm install -g @angular/cli
  script:
  - ng build 

after_success:
  - firebase deploy --token 