language: node_js

node_js:
  - stable
branches:
  only:
    - master

before-script:
  - npm install -g @angular/cli

 
script:
  - ng build 
install:
   - npm install -g firebase-tools   

after_success:
  - firebase deploy --token 